---
title: "PLotting"
author: "Leanne"
date: "13 October 2017"
output: html_document
---
```{r}
gapminder
```
```{r}
library(ggplot2)
ggplot(data = gapminder,aes(x = gdpPercap, y = lifeExp)) + geom_point()
```
```{r}
ggplot(data = gapminder, aes(x = year, y = lifeExp)) + geom_point()
```
```{r}
ggplot(data = gapminder, aes(x = year, y = lifeExp, color=continent)) + geom_point()
```
```{r}
ggplot(data = gapminder, aes(x=year, y=lifeExp, by= country, color=continent)) + geom_line()

```
```{r}
ggplot(data = gapminder, aes(x=year, y=lifeExp, by= country, )) + geom_point()+geom_line(aes(color=continent))
```
```{r}
ggplot(data = gapminder,aes(x = gdpPercap, y = lifeExp, color=continent)) + geom_point()
```
```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp)) + geom_point(alpha = 0.5) + scale_x_log10()
```

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp)) + geom_point(aes(alpha=continent)) + scale_x_log10()
```
```{r}
ggplot(data = gapminder, aes(x=gdpPercap, y= lifeExp)) + geom_point(aes(color=continent, alpha=continent)) + scale_x_log10() + geom_smooth(method="lm", size=0.5)
```
```{r}
starts.with <- substr(gapminder$country, start = 1, stop = 1) 
az.countries <- gapminder[starts.with %in% c("A", "Z"),]
ggplot(data = az.countries, aes(x = year, y = lifeExp, color = country)) + geom_line() + facet_wrap(~continent)


```
```{r}
ggplot(data = gapminder, aes(x=gdpPercap, fill=continent)) + geom_density()
```
```{r}
ggplot(data = gapminder, aes(x=gdpPercap, fill=continent)) + geom_density() + scale_x_log10()
```

```{r}
ggplot(data = gapminder, aes(x=gdpPercap, fill=continent)) + geom_density(alpha=0.5) + scale_x_log10() + facet_wrap(~year)
```

